[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  VITE_SUPABASE_URL = "https://xyzcompany.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."


# ✅ React / Vite SPA yönlendirmeleri
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Farcaster manifest dosyası MIME tipi düzeltmesi
[[headers]]
  for = "/farcaster.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
